FROM quay.io/wildfly/wildfly:26.1.3.Final-jdk17

ENV POSTGRES_DB studs
ENV POSTGRES_USER UNI_NUMBER
ENV POSTGRES_PASSWORD PASSWORD
ENV PORTBASE 32318
ENV JCONSOLE_PORT 32321

RUN /opt/jboss/wildfly/bin/add-user.sh admin Admin#70365 --silent

COPY target/interactive-graph-ui-1.0-SNAPSHOT.war /opt/jboss/wildfly/standalone/deployments/

EXPOSE $PORTBASE $JCONSOLE_PORT

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]