CREATE SCHEMA IF NOT EXISTS UNI_NUMBER;

GRANT ALL PRIVILEGES ON SCHEMA UNI_NUMBER TO s666666;

CREATE TABLE UNI_NUMBER.point_model
(
    id     SERIAL PRIMARY KEY,
    x      DOUBLE PRECISION NOT NULL,
    y      DOUBLE PRECISION NOT NULL,
    r      DOUBLE PRECISION NOT NULL,
    result BOOLEAN
);

GRANT ALL PRIVILEGES ON TABLE UNI_NUMBER.point_model TO s666666;
GRANT ALL PRIVILEGES ON SEQUENCE UNI_NUMBER.point_model_id_seq TO s666666;
